alteração do html
GuilhermeRochaR/Banco pull request #2
Opened 2024-11-26 19:31 UTC by YanGarrido

2024-11-26 19:33 UTC, GuilhermeRochaR approved these changes

2024-11-26 19:34 UTC, LuisMagnoLima commented on index.html
por favor melhore

2024-11-26 19:35 UTC, LuisMagnoLima requested changes
Tem que melhorar

2024-11-26 19:55 UTC, GuilhermeRochaR approved these changes, later dismissed

2024-11-27 14:41 UTC, GuilhermeRochaR approved these changes

2024-11-27 14:47 UTC, LuisMagnoLima approved these changes

2024-11-27 14:50 UTC, Vsag2005 approved these changes

2024-11-27 14:51 UTC, merged